spring.application.name=prescription
spring.datasource.url=jdbc:mysql://187.127.187.65:3306/indigorx
spring.datasource.username=root
spring.datasource.password=Athul@97

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configurations (optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=aksjcjhsdbciueqouuwqhwhbdakasixasbcbasicbsdjcju
jwt.expiration=86400000
server.port=9090



# Postmark
postmark.api.token=b6ce4c63-1434-43e6-9d9a-188b2510d65b
postmark.from.email=info@indigorx.me
postmark.from.name=IndigoRx
app.frontend.url=https://indigorx.me

# OTP Settings
otp.expiry.minutes=10
otp.max.requests.per.hour=5
otp.length=6

# Password Reset
password.reset.max.requests.per.hour=3